name: Generate Latest macOS Tahoe ISO file

on:
  workflow_dispatch:

run-name: Generate macOS Tahoe ISO file 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          # Remove large, unused packages
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /Library/Android
          
          # Remove cached tools and user caches
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf "$HOME/.cache"
          
          # Remove Xcode to free ~10–15GB
          sudo rm -rf /Applications/Xcode.app
          
          # Clean temporary files
          sudo rm -rf /tmp/*
          
          df -h
      - name: Download macOS Installer
        run: |
          curl -L -o /tmp/InstallAssistant.pkg https://swcdn.apple.com/content/downloads/27/44/093-50844-A_ADFZL6MD5J/3p92a0vzjzewywyitfwajte1w5t8t4pzts/InstallAssistant.pkg
      - name: Install the assistant
        run: |
          sudo installer -pkg /tmp/InstallAssistant.pkg -target /
      - name: Generate macOS Installer
        run: |
          sudo hdiutil create -o /tmp/Tahoe -size 20000m -volname 'Tahoe' -layout SPUD -fs HFS+J
          sudo hdiutil attach /tmp/Tahoe.dmg -noverify -mountpoint /Volumes/Tahoe
          sleep 10
          sudo /Applications/'Install macOS Tahoe'.app/Contents/Resources/createinstallmedia --volume /Volumes/Tahoe --nointeraction
          sudo hdiutil detach -force /Volumes/Install\ macOS\ Tahoe
          sudo hdiutil convert /tmp/Tahoe.dmg -format UDTO -o /tmp/Tahoe.cdr
          sleep 10
          sudo mv /tmp/tahoe.cdr /tmp/tahoe.iso
      - name: Upload ISO image
        uses: actions/upload-artifact@v4
        with:
          name: tahoe.iso
          path: /tmp/tahoe.iso
          compression-level: 9
